export const theme = {
  colors: {
    background: '#262b2e',
    foreground: '#fff',
    card: '#fff',
    cardForeground: '#262b2e',
    popover: '#fff',
    popoverForeground: '#262b2e',
    primary: '#262b2e',
    primaryForeground: '#fff',
    secondary: '#c98f42',
    secondaryForeground: '#262b2e',
    muted: '#f5f5f5',
    mutedForeground: '#b0b0b0',
    accent: '#8d7250',
    accentForeground: '#fff',
    destructive: '#ff4d4f',
    destructiveForeground: '#fff',
    border: '#e5e7eb',
    input: '#e5e7eb',
    ring: '#8d7250',
    saffron: '#8d7250',
    darkpurple: '#d4c5b0',
    darkgreen: '#FFFFFF',
    // Social Media Colors
    bookingHighlight: '#ff3b30',
    socialInstagram: '#e1306c',
    socialTwitter: '#1da1f2',
    socialTiktok: '#000000',
    socialFacebook: '#1877f3',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  typography: {
    fontSizes: {
      xs: 12,
      sm: 14,
      base: 16,
      lg: 18,
      xl: 20,
      '2xl': 24,
      '3xl': 30,
      '4xl': 36,
    },
    fontWeights: {
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
  },
} as const;

export type Theme = typeof theme; 